try:
    from backend.database import Base, engine, SessionLocal
    from backend.models import Crop, GovtScheme, Disease, WeatherAdvice, SoilProfile
except ImportError:
    from database import Base, engine, SessionLocal
    from models import Crop, GovtScheme, Disease, WeatherAdvice, SoilProfile


crops_data = [
    {"name_en": "Wheat", "name_hi": "गेहूं", "soil_type": "Loamy, Clay", "season": "Rabi", "state": "Punjab, Haryana, Uttar Pradesh", "water_need": "Medium", "expected_yield_qtl": "50-60", "market_price_min": 2015, "market_price_max": 2200, "growing_days": 120, "fertilizer": "NPK 120:60:40 with split nitrogen", "description_hi": "रबी की मुख्य फसल, समय पर सिंचाई और खरपतवार नियंत्रण जरूरी।"},
    {"name_en": "Rice", "name_hi": "धान", "soil_type": "Clay, Loamy", "season": "Kharif", "state": "Uttar Pradesh, Bihar, West Bengal", "water_need": "High", "expected_yield_qtl": "40-50", "market_price_min": 2183, "market_price_max": 2400, "growing_days": 130, "fertilizer": "NPK 100:50:50 with zinc", "description_hi": "अधिक पानी वाली खरीफ फसल, नर्सरी प्रबंधन महत्वपूर्ण।"},
    {"name_en": "Maize", "name_hi": "मक्का", "soil_type": "Loamy, Sandy", "season": "Kharif", "state": "Madhya Pradesh, Rajasthan", "water_need": "Medium", "expected_yield_qtl": "35-45", "market_price_min": 1962, "market_price_max": 2100, "growing_days": 90, "fertilizer": "NPK 90:45:30", "description_hi": "कम अवधि की फसल, जल निकास अच्छा रखें।"},
    {"name_en": "Mustard", "name_hi": "सरसों", "soil_type": "Loamy", "season": "Rabi", "state": "Rajasthan, Haryana", "water_need": "Low", "expected_yield_qtl": "12-15", "market_price_min": 5450, "market_price_max": 5800, "growing_days": 110, "fertilizer": "NPK 80:40:20 with sulfur", "description_hi": "कम पानी में सफल, सल्फर देने से तेल प्रतिशत बढ़ता है।"},
    {"name_en": "Cotton", "name_hi": "कपास", "soil_type": "Black, Loamy", "season": "Kharif", "state": "Maharashtra, Gujarat", "water_need": "Medium", "expected_yield_qtl": "20-25", "market_price_min": 6080, "market_price_max": 6600, "growing_days": 180, "fertilizer": "NPK 100:50:50 plus micronutrients", "description_hi": "लंबी अवधि की नकदी फसल, कीट निगरानी नियमित करें।"},
    {"name_en": "Sugarcane", "name_hi": "गन्ना", "soil_type": "Loamy, Clay", "season": "Annual", "state": "Uttar Pradesh, Maharashtra", "water_need": "Very High", "expected_yield_qtl": "300-400", "market_price_min": 340, "market_price_max": 360, "growing_days": 365, "fertilizer": "High nitrogen + FYM", "description_hi": "बहुत पानी और पोषण मांगने वाली वार्षिक फसल।"},
    {"name_en": "Soybean", "name_hi": "सोयाबीन", "soil_type": "Loamy, Black", "season": "Kharif", "state": "Madhya Pradesh, Maharashtra", "water_need": "Medium", "expected_yield_qtl": "20-25", "market_price_min": 4300, "market_price_max": 4600, "growing_days": 90, "fertilizer": "Rhizobium seed treatment + SSP", "description_hi": "दलहनी-तिलहनी फसल, बीजोपचार लाभकारी।"},
    {"name_en": "Groundnut", "name_hi": "मूंगफली", "soil_type": "Sandy, Loamy", "season": "Kharif", "state": "Gujarat, Andhra Pradesh", "water_need": "Medium", "expected_yield_qtl": "15-20", "market_price_min": 5550, "market_price_max": 5900, "growing_days": 110, "fertilizer": "Gypsum and calcium rich dose", "description_hi": "हल्की मिट्टी में अच्छी उपज, फूल आने पर नमी रखें।"},
    {"name_en": "Gram", "name_hi": "चना", "soil_type": "Loamy, Clay", "season": "Rabi", "state": "Madhya Pradesh, Rajasthan", "water_need": "Low", "expected_yield_qtl": "15-20", "market_price_min": 5440, "market_price_max": 5700, "growing_days": 100, "fertilizer": "DAP basal, Rhizobium culture", "description_hi": "कम सिंचाई में सफल दलहनी फसल।"},
    {"name_en": "Tomato", "name_hi": "टमाटर", "soil_type": "Loamy", "season": "All", "state": "Andhra Pradesh, Karnataka", "water_need": "High", "expected_yield_qtl": "100-150", "market_price_min": 1000, "market_price_max": 3000, "growing_days": 70, "fertilizer": "NPK drip fertigation", "description_hi": "उच्च मूल्य फसल, रोग प्रबंधन अनिवार्य।"},
    {"name_en": "Potato", "name_hi": "आलू", "soil_type": "Loamy, Sandy", "season": "Rabi", "state": "Uttar Pradesh, West Bengal", "water_need": "Medium", "expected_yield_qtl": "120-150", "market_price_min": 800, "market_price_max": 1500, "growing_days": 90, "fertilizer": "Balanced NPK + potash", "description_hi": "कंद विकास हेतु पोटाश जरूरी।"},
    {"name_en": "Onion", "name_hi": "प्याज", "soil_type": "Loamy", "season": "Rabi, Kharif", "state": "Maharashtra, Madhya Pradesh", "water_need": "Medium", "expected_yield_qtl": "80-100", "market_price_min": 1000, "market_price_max": 2500, "growing_days": 120, "fertilizer": "NPK + sulfur", "description_hi": "भंडारण योग्य फसल, संतुलित पोषण आवश्यक।"},
    {"name_en": "Turmeric", "name_hi": "हल्दी", "soil_type": "Loamy, Clay", "season": "Kharif", "state": "Andhra Pradesh, Telangana", "water_need": "High", "expected_yield_qtl": "25-30", "market_price_min": 7000, "market_price_max": 9000, "growing_days": 270, "fertilizer": "FYM + NPK with mulch", "description_hi": "मसाला फसल, नमी और जैविक खाद लाभकारी।"},
    {"name_en": "Pigeon Pea", "name_hi": "अरहर", "soil_type": "Sandy, Loamy", "season": "Kharif", "state": "Maharashtra, Uttar Pradesh", "water_need": "Low", "expected_yield_qtl": "12-15", "market_price_min": 7000, "market_price_max": 7400, "growing_days": 150, "fertilizer": "Phosphorus rich basal dose", "description_hi": "लंबी अवधि की दलहनी फसल।"},
    {"name_en": "Moong", "name_hi": "मूंग", "soil_type": "Sandy, Loamy", "season": "Zaid, Kharif", "state": "Rajasthan, Uttar Pradesh", "water_need": "Low", "expected_yield_qtl": "8-12", "market_price_min": 7755, "market_price_max": 8200, "growing_days": 65, "fertilizer": "Rhizobium treatment + light NPK", "description_hi": "कम अवधि और कम पानी वाली फसल।"},
    {"name_en": "Urad", "name_hi": "उड़द", "soil_type": "Loamy", "season": "Kharif", "state": "Madhya Pradesh, Uttar Pradesh", "water_need": "Low", "expected_yield_qtl": "8-10", "market_price_min": 6500, "market_price_max": 7200, "growing_days": 80, "fertilizer": "DAP basal + biofertilizer", "description_hi": "दलहनी फसल, जलभराव से बचाएं।"},
    {"name_en": "Sorghum", "name_hi": "ज्वार", "soil_type": "Black, Loamy", "season": "Kharif, Rabi", "state": "Maharashtra, Karnataka", "water_need": "Low", "expected_yield_qtl": "18-25", "market_price_min": 3100, "market_price_max": 3600, "growing_days": 105, "fertilizer": "NPK 80:40:0", "description_hi": "सूखा सहनशील मोटा अनाज।"},
    {"name_en": "Pearl Millet", "name_hi": "बाजरा", "soil_type": "Sandy, Loamy", "season": "Kharif", "state": "Rajasthan, Haryana", "water_need": "Low", "expected_yield_qtl": "12-20", "market_price_min": 2350, "market_price_max": 2800, "growing_days": 80, "fertilizer": "NPK 60:30:0", "description_hi": "कम वर्षा क्षेत्रों के लिए उपयुक्त।"},
    {"name_en": "Barley", "name_hi": "जौ", "soil_type": "Loamy", "season": "Rabi", "state": "Rajasthan, Uttar Pradesh", "water_need": "Low", "expected_yield_qtl": "20-25", "market_price_min": 1700, "market_price_max": 2100, "growing_days": 110, "fertilizer": "NPK 60:30:20", "description_hi": "ठंडे मौसम की अनाज फसल।"},
    {"name_en": "Linseed", "name_hi": "अलसी", "soil_type": "Loamy, Clay", "season": "Rabi", "state": "Madhya Pradesh, Chhattisgarh", "water_need": "Low", "expected_yield_qtl": "7-10", "market_price_min": 5500, "market_price_max": 6200, "growing_days": 120, "fertilizer": "Low nitrogen, higher phosphorus", "description_hi": "तिलहनी फसल, कम सिंचाई में सफल।"},
    {"name_en": "Sunflower", "name_hi": "सूरजमुखी", "soil_type": "Loamy", "season": "Kharif, Rabi", "state": "Karnataka, Andhra Pradesh", "water_need": "Medium", "expected_yield_qtl": "10-15", "market_price_min": 5200, "market_price_max": 5800, "growing_days": 95, "fertilizer": "NPK 60:60:40", "description_hi": "तिलहनी फसल, मध्यम पानी की जरूरत।"},
    {"name_en": "Castor", "name_hi": "अरंडी", "soil_type": "Sandy, Loamy", "season": "Kharif", "state": "Gujarat, Rajasthan", "water_need": "Low", "expected_yield_qtl": "10-14", "market_price_min": 6200, "market_price_max": 7000, "growing_days": 160, "fertilizer": "NPK 80:40:20", "description_hi": "सूखा सहनशील नकदी फसल।"},
    {"name_en": "Jute", "name_hi": "जूट", "soil_type": "Alluvial, Loamy", "season": "Kharif", "state": "West Bengal, Assam", "water_need": "High", "expected_yield_qtl": "18-22", "market_price_min": 4500, "market_price_max": 5200, "growing_days": 120, "fertilizer": "Nitrogen rich fertilization", "description_hi": "रेशा फसल, आर्द्र जलवायु में अच्छी।"},
    {"name_en": "Brinjal", "name_hi": "बैंगन", "soil_type": "Loamy", "season": "All", "state": "West Bengal, Odisha", "water_need": "Medium", "expected_yield_qtl": "120-180", "market_price_min": 1200, "market_price_max": 2800, "growing_days": 85, "fertilizer": "FYM + NPK split dose", "description_hi": "सब्जी फसल, फल छेदक कीट से बचाव करें।"},
    {"name_en": "Chilli", "name_hi": "मिर्च", "soil_type": "Loamy, Sandy", "season": "Kharif, Rabi", "state": "Andhra Pradesh, Telangana", "water_need": "Medium", "expected_yield_qtl": "25-40", "market_price_min": 7000, "market_price_max": 12000, "growing_days": 150, "fertilizer": "NPK + calcium nitrate", "description_hi": "मसाला फसल, थ्रिप्स नियंत्रण जरूरी।"},
    {"name_en": "Garlic", "name_hi": "लहसुन", "soil_type": "Loamy", "season": "Rabi", "state": "Madhya Pradesh, Gujarat", "water_need": "Medium", "expected_yield_qtl": "45-60", "market_price_min": 3000, "market_price_max": 8000, "growing_days": 130, "fertilizer": "Sulfur and potash rich nutrition", "description_hi": "उच्च मूल्य मसाला फसल।"},
    {"name_en": "Ginger", "name_hi": "अदरक", "soil_type": "Loamy, Clay", "season": "Kharif", "state": "Kerala, Karnataka", "water_need": "High", "expected_yield_qtl": "60-90", "market_price_min": 2500, "market_price_max": 6000, "growing_days": 240, "fertilizer": "Organic manure + NPK", "description_hi": "जैविक पदार्थ समृद्ध मिट्टी में अच्छा उत्पादन।"},
    {"name_en": "Cauliflower", "name_hi": "फूलगोभी", "soil_type": "Loamy", "season": "Rabi", "state": "Bihar, Uttar Pradesh", "water_need": "Medium", "expected_yield_qtl": "80-120", "market_price_min": 1000, "market_price_max": 2200, "growing_days": 95, "fertilizer": "NPK + boron", "description_hi": "ठंडे मौसम की लोकप्रिय सब्जी।"},
    {"name_en": "Cabbage", "name_hi": "पत्ता गोभी", "soil_type": "Loamy", "season": "Rabi", "state": "West Bengal, Odisha", "water_need": "Medium", "expected_yield_qtl": "100-140", "market_price_min": 900, "market_price_max": 2000, "growing_days": 90, "fertilizer": "Balanced NPK and organic carbon", "description_hi": "मध्यम अवधि सब्जी फसल।"},
    {"name_en": "Spinach", "name_hi": "पालक", "soil_type": "Loamy", "season": "All", "state": "Punjab, Haryana", "water_need": "Medium", "expected_yield_qtl": "50-80", "market_price_min": 1200, "market_price_max": 3000, "growing_days": 45, "fertilizer": "Nitrogen rich light doses", "description_hi": "तेजी से तैयार होने वाली पत्तेदार सब्जी।"},
    {"name_en": "Bitter Gourd", "name_hi": "करेला", "soil_type": "Loamy, Sandy", "season": "Zaid, Kharif", "state": "Uttar Pradesh, Bihar", "water_need": "Medium", "expected_yield_qtl": "70-100", "market_price_min": 2000, "market_price_max": 4500, "growing_days": 70, "fertilizer": "FYM + NPK in pits", "description_hi": "लता वाली सब्जी, ट्रेलिसिंग उपयोगी।"},
    {"name_en": "Lady Finger", "name_hi": "भिंडी", "soil_type": "Loamy, Sandy", "season": "Kharif, Zaid", "state": "Gujarat, Maharashtra", "water_need": "Medium", "expected_yield_qtl": "60-90", "market_price_min": 1800, "market_price_max": 4000, "growing_days": 60, "fertilizer": "NPK 80:40:40", "description_hi": "तेज बढ़वार वाली सब्जी, पीला मोजेक रोग पर ध्यान दें।"},
    {"name_en": "Millet Mix", "name_hi": "मिलेट मिश्रण", "soil_type": "Sandy, Loamy", "season": "Kharif", "state": "Rajasthan, Karnataka", "water_need": "Low", "expected_yield_qtl": "10-18", "market_price_min": 2600, "market_price_max": 3800, "growing_days": 85, "fertilizer": "Low input with biofertilizers", "description_hi": "पोषक और सूखा सहनशील विकल्प।"},
    {"name_en": "Sesame", "name_hi": "तिल", "soil_type": "Sandy, Loamy", "season": "Kharif", "state": "Gujarat, Uttar Pradesh", "water_need": "Low", "expected_yield_qtl": "5-8", "market_price_min": 8500, "market_price_max": 9500, "growing_days": 95, "fertilizer": "Phosphorus rich basal dose", "description_hi": "कम पानी और कम लागत वाली तिलहनी।"},
    {"name_en": "Lentil", "name_hi": "मसूर", "soil_type": "Loamy, Clay", "season": "Rabi", "state": "Madhya Pradesh, Uttar Pradesh", "water_need": "Low", "expected_yield_qtl": "8-12", "market_price_min": 5800, "market_price_max": 6500, "growing_days": 110, "fertilizer": "Rhizobium + phosphorus", "description_hi": "रबी की दलहनी फसल, उर्वरता बढ़ाती है।"},
]

schemes_data = [
    {"name_en": "PM-KISAN", "name_hi": "पीएम-किसान सम्मान निधि", "ministry": "Ministry of Agriculture", "benefit_en": "Income support of Rs 6000 per year in 3 installments.", "benefit_hi": "किसानों को सालाना 6000 रुपये 3 किस्तों में।", "eligibility_en": "Small and marginal farmers with up to 2 hectares.", "eligibility_hi": "2 हेक्टेयर तक भूमि वाले छोटे और सीमांत किसान।", "amount": "Rs 6000", "frequency": "Yearly (3 installments)", "official_url": "https://pmkisan.gov.in", "launch_year": 2019, "active": True},
    {"name_en": "PM Fasal Bima Yojana", "name_hi": "प्रधानमंत्री फसल बीमा योजना", "ministry": "Ministry of Agriculture", "benefit_en": "Crop insurance with low premium rates 1.5%-5%.", "benefit_hi": "1.5%-5% प्रीमियम पर फसल बीमा सुरक्षा।", "eligibility_en": "All farmers including tenant farmers.", "eligibility_hi": "सभी किसान, बटाईदार किसान भी शामिल।", "amount": "Insurance cover", "frequency": "Per season", "official_url": "https://pmfby.gov.in", "launch_year": 2016, "active": True},
    {"name_en": "Kisan Credit Card", "name_hi": "किसान क्रेडिट कार्ड", "ministry": "Ministry of Finance", "benefit_en": "Credit up to Rs 3 lakh at concessional interest.", "benefit_hi": "3 लाख तक ऋण, रियायती ब्याज दर पर।", "eligibility_en": "Farmers with cultivable land and bank account.", "eligibility_hi": "खेती योग्य भूमि और बैंक खाता रखने वाले किसान।", "amount": "Up to Rs 3 lakh", "frequency": "Revolving credit", "official_url": "https://www.myscheme.gov.in/schemes/kcc", "launch_year": 1998, "active": True},
    {"name_en": "Soil Health Card", "name_hi": "मृदा स्वास्थ्य कार्ड योजना", "ministry": "Ministry of Agriculture", "benefit_en": "Free soil testing and nutrient recommendations every 2 years.", "benefit_hi": "हर 2 साल में मुफ्त मिट्टी जांच और पोषण सलाह।", "eligibility_en": "All registered farmers.", "eligibility_hi": "सभी पंजीकृत किसान।", "amount": "Free service", "frequency": "Every 2 years", "official_url": "https://soilhealth.dac.gov.in", "launch_year": 2015, "active": True},
    {"name_en": "PM Sinchai Yojana", "name_hi": "प्रधानमंत्री कृषि सिंचाई योजना", "ministry": "Ministry of Jal Shakti", "benefit_en": "Subsidy up to 55% for drip/sprinkler irrigation.", "benefit_hi": "ड्रिप/स्प्रिंकलर पर 55% तक सब्सिडी।", "eligibility_en": "Farmers adopting micro-irrigation.", "eligibility_hi": "सूक्ष्म सिंचाई अपनाने वाले किसान।", "amount": "Up to 55% subsidy", "frequency": "One-time/project based", "official_url": "https://pmksy.gov.in", "launch_year": 2015, "active": True},
    {"name_en": "e-NAM", "name_hi": "ई-नाम", "ministry": "Ministry of Agriculture", "benefit_en": "Online mandi platform for transparent price discovery.", "benefit_hi": "पारदर्शी भाव खोज के लिए ऑनलाइन मंडी प्लेटफॉर्म।", "eligibility_en": "Farmers and traders registered in e-NAM mandis.", "eligibility_hi": "ई-नाम मंडियों में पंजीकृत किसान/व्यापारी।", "amount": "Market access", "frequency": "Anytime", "official_url": "https://www.enam.gov.in", "launch_year": 2016, "active": True},
    {"name_en": "Paramparagat Krishi Vikas Yojana", "name_hi": "परंपरागत कृषि विकास योजना", "ministry": "Ministry of Agriculture", "benefit_en": "Support of Rs 50,000/hectare for organic farming clusters.", "benefit_hi": "जैविक खेती क्लस्टर हेतु 50,000 रुपये/हेक्टेयर सहायता।", "eligibility_en": "Farmers willing to adopt organic farming in groups.", "eligibility_hi": "समूह में जैविक खेती अपनाने वाले किसान।", "amount": "Rs 50,000/hectare", "frequency": "Project period", "official_url": "https://pgsindia-ncof.gov.in", "launch_year": 2015, "active": True},
    {"name_en": "Agriculture Infrastructure Fund", "name_hi": "कृषि अवसंरचना कोष", "ministry": "Ministry of Agriculture", "benefit_en": "Credit support from Rs 1 lakh crore fund for post-harvest infrastructure.", "benefit_hi": "कटाई बाद ढांचे हेतु 1 लाख करोड़ कोष से ऋण सहायता।", "eligibility_en": "Farmers, FPOs, PACS, agri-entrepreneurs.", "eligibility_hi": "किसान, एफपीओ, पैक्स और कृषि उद्यमी।", "amount": "Credit linked support", "frequency": "As sanctioned", "official_url": "https://agriinfra.dac.gov.in", "launch_year": 2020, "active": True},
    {"name_en": "PM Kusum Yojana", "name_hi": "पीएम कुसुम योजना", "ministry": "Ministry of New and Renewable Energy", "benefit_en": "Solar pump subsidy up to 60%.", "benefit_hi": "सोलर पंप पर 60% तक सब्सिडी।", "eligibility_en": "Farmers and farmer groups with irrigation needs.", "eligibility_hi": "सिंचाई आवश्यकता वाले किसान और किसान समूह।", "amount": "Up to 60% subsidy", "frequency": "One-time", "official_url": "https://mnre.gov.in/pm-kusum", "launch_year": 2019, "active": True},
    {"name_en": "RKVY", "name_hi": "राष्ट्रीय कृषि विकास योजना", "ministry": "Ministry of Agriculture", "benefit_en": "Flexible funding for agriculture innovation projects.", "benefit_hi": "कृषि नवाचार परियोजनाओं के लिए लचीला फंड।", "eligibility_en": "States, institutions, and approved farmer groups.", "eligibility_hi": "राज्य, संस्थान और अनुमोदित किसान समूह।", "amount": "Project based assistance", "frequency": "Scheme cycle", "official_url": "https://rkvy.nic.in", "launch_year": 2007, "active": True},
    {"name_en": "Rashtriya Krishi Bima Yojana", "name_hi": "राष्ट्रीय कृषि बीमा योजना", "ministry": "Ministry of Agriculture", "benefit_en": "Comprehensive multi-risk crop cover.", "benefit_hi": "बहु-जोखिम फसल बीमा सुरक्षा।", "eligibility_en": "Farmers in notified areas and crops.", "eligibility_hi": "अधिसूचित क्षेत्रों/फसलों के किसान।", "amount": "Insurance support", "frequency": "Per season", "official_url": "https://www.india.gov.in", "launch_year": 1999, "active": True},
    {"name_en": "Kisan Suvidha App", "name_hi": "किसान सुविधा ऐप", "ministry": "Ministry of Agriculture", "benefit_en": "Free advisory, weather updates, and mandi prices.", "benefit_hi": "मुफ्त सलाह, मौसम और मंडी भाव जानकारी।", "eligibility_en": "All farmers with smartphone access.", "eligibility_hi": "स्मार्टफोन उपयोग करने वाले सभी किसान।", "amount": "Free", "frequency": "Daily", "official_url": "https://mkisan.gov.in", "launch_year": 2016, "active": True},
]

diseases_data = [
    {"name_en": "Wheat Rust", "name_hi": "गेहूं का रतुआ", "crop_affected": "Wheat", "symptoms_en": "Orange or brown pustules on leaves and stems.", "symptoms_hi": "पत्तियों और तनों पर नारंगी/भूरे दाने।", "cause": "Puccinia fungi", "organic_treatment": "Neem extract spray and remove infected leaves.", "chemical_treatment": "Spray Propiconazole 25% EC.", "prevention": "Use resistant varieties and avoid excess nitrogen.", "severity": "high"},
    {"name_en": "Rice Blast", "name_hi": "धान का झुलसा", "crop_affected": "Rice", "symptoms_en": "Gray lesions with dark border on leaves.", "symptoms_hi": "पत्तियों पर धूसर धब्बे, किनारा गहरा।", "cause": "Magnaporthe oryzae fungus", "organic_treatment": "Trichoderma seed treatment and balanced nutrition.", "chemical_treatment": "Spray Tricyclazole as recommended.", "prevention": "Use certified seed and proper spacing.", "severity": "high"},
    {"name_en": "Cotton Bollworm", "name_hi": "कपास की सुंडी", "crop_affected": "Cotton", "symptoms_en": "Holes in bolls and damaged flowers.", "symptoms_hi": "बोल में छेद और फूलों को नुकसान।", "cause": "Helicoverpa armigera", "organic_treatment": "Install pheromone traps and neem spray.", "chemical_treatment": "Spray Chlorpyrifos or Emamectin benzoate.", "prevention": "Timely monitoring and trap crop use.", "severity": "high"},
    {"name_en": "Powdery Mildew", "name_hi": "सफेद चूर्णी रोग", "crop_affected": "Multiple crops", "symptoms_en": "White powdery coating on leaves.", "symptoms_hi": "पत्तियों पर सफेद चूर्ण जैसा आवरण।", "cause": "Fungal infection", "organic_treatment": "Cow milk diluted spray and sulfur dust.", "chemical_treatment": "Wettable sulfur or Hexaconazole spray.", "prevention": "Improve air circulation and avoid overcrowding.", "severity": "medium"},
    {"name_en": "Late Blight", "name_hi": "आलू का झुलसा", "crop_affected": "Potato", "symptoms_en": "Dark water-soaked lesions and rapid leaf death.", "symptoms_hi": "काले पानी जैसे धब्बे और पत्ती सूखना।", "cause": "Phytophthora infestans", "organic_treatment": "Copper based organic fungicide.", "chemical_treatment": "Mancozeb + Metalaxyl spray.", "prevention": "Avoid leaf wetness and use healthy seed tubers.", "severity": "high"},
    {"name_en": "Tomato Leaf Curl", "name_hi": "टमाटर पत्ती मुड़न", "crop_affected": "Tomato", "symptoms_en": "Leaf curling, yellowing, stunted growth.", "symptoms_hi": "पत्तियां मुड़ना, पीली पड़ना, बढ़वार रुकना।", "cause": "Virus transmitted by whitefly", "organic_treatment": "Yellow sticky traps and neem oil.", "chemical_treatment": "Imidacloprid for whitefly control.", "prevention": "Use resistant seedlings and net nursery.", "severity": "high"},
    {"name_en": "Downy Mildew", "name_hi": "डाउनी मिल्ड्यू", "crop_affected": "Vegetables", "symptoms_en": "Yellow patches and gray fuzzy growth underside.", "symptoms_hi": "पीले धब्बे और नीचे धूसर फफूंद।", "cause": "Oomycete pathogens", "organic_treatment": "Bordeaux mixture and sanitation.", "chemical_treatment": "Dimethomorph based spray.", "prevention": "Reduce humidity and ensure drainage.", "severity": "medium"},
    {"name_en": "Bacterial Blight", "name_hi": "जीवाणु झुलसा", "crop_affected": "Rice, Cotton", "symptoms_en": "Water-soaked spots turning brown.", "symptoms_hi": "पानी जैसे धब्बे जो भूरे हो जाते हैं।", "cause": "Bacterial infection", "organic_treatment": "Use bio-control consortia and clean irrigation.", "chemical_treatment": "Copper oxychloride spray.", "prevention": "Certified seed and field hygiene.", "severity": "high"},
    {"name_en": "Aphid Infestation", "name_hi": "माहू प्रकोप", "crop_affected": "Pulses, Vegetables", "symptoms_en": "Small insects on soft shoots and curling leaves.", "symptoms_hi": "कोमल भागों पर छोटे कीट और पत्तियां मुड़ना।", "cause": "Aphid attack", "organic_treatment": "Neem oil 3 ml per liter.", "chemical_treatment": "Thiamethoxam low dose spray.", "prevention": "Encourage ladybird beetles and early monitoring.", "severity": "medium"},
    {"name_en": "Root Rot", "name_hi": "जड़ सड़न", "crop_affected": "Pulses, Vegetables", "symptoms_en": "Wilting and brown decayed roots.", "symptoms_hi": "मुरझाना और जड़ों का भूरा सड़ना।", "cause": "Fusarium and overwatering", "organic_treatment": "Trichoderma mixed in FYM.", "chemical_treatment": "Carbendazim soil drench.", "prevention": "Avoid waterlogging and rotate crops.", "severity": "high"},
    {"name_en": "Stem Borer", "name_hi": "तना छेदक", "crop_affected": "Rice, Maize", "symptoms_en": "Dead heart and white ear symptoms.", "symptoms_hi": "डेड हार्ट और सफेद बालियां।", "cause": "Insect larvae", "organic_treatment": "Light traps and pheromone traps.", "chemical_treatment": "Chlorantraniliprole granules.", "prevention": "Timely sowing and clean stubble.", "severity": "high"},
    {"name_en": "Leaf Miner", "name_hi": "पत्ती सुरंगी कीट", "crop_affected": "Vegetables", "symptoms_en": "Serpentine tunnels on leaves.", "symptoms_hi": "पत्तियों में सांप जैसी सुरंगें।", "cause": "Leaf miner larvae", "organic_treatment": "Sticky traps and neem spray.", "chemical_treatment": "Abamectin targeted spray.", "prevention": "Remove infested leaves early.", "severity": "medium"},
    {"name_en": "Thrips", "name_hi": "थ्रिप्स प्रकोप", "crop_affected": "Chilli, Onion", "symptoms_en": "Silvery streaks and leaf curling.", "symptoms_hi": "चांदी जैसी धारियां और पत्ती मुड़ना।", "cause": "Thrips insects", "organic_treatment": "Blue sticky traps and neem extract.", "chemical_treatment": "Spinosad spray.", "prevention": "Avoid moisture stress and monitor weekly.", "severity": "medium"},
    {"name_en": "Fusarium Wilt", "name_hi": "फ्यूजेरियम विल्ट", "crop_affected": "Tomato, Chilli", "symptoms_en": "Yellowing from lower leaves and wilting.", "symptoms_hi": "नीचे से पत्तियां पीली और पौधा मुरझाना।", "cause": "Fusarium fungus", "organic_treatment": "Trichoderma and raised beds.", "chemical_treatment": "Carbendazim drench.", "prevention": "Use resistant varieties and rotate crops.", "severity": "high"},
    {"name_en": "Cercospora Leaf Spot", "name_hi": "सर्कोस्पोरा पत्ती धब्बा", "crop_affected": "Groundnut, Soybean", "symptoms_en": "Circular brown spots with yellow halo.", "symptoms_hi": "भूरे गोल धब्बे और पीला घेरा।", "cause": "Cercospora fungus", "organic_treatment": "Compost tea spray and sanitation.", "chemical_treatment": "Mancozeb spray.", "prevention": "Seed treatment and residue management.", "severity": "medium"},
    {"name_en": "Alternaria Blight", "name_hi": "अल्टरनेरिया झुलसा", "crop_affected": "Mustard, Tomato", "symptoms_en": "Concentric ring spots on leaves.", "symptoms_hi": "पत्तियों पर गोल-गोल घेरों वाले धब्बे।", "cause": "Alternaria fungus", "organic_treatment": "Neem cake and biofungicide.", "chemical_treatment": "Difenoconazole spray.", "prevention": "Balanced fertilization and spacing.", "severity": "medium"},
    {"name_en": "Smut", "name_hi": "कंडवा रोग", "crop_affected": "Wheat, Barley", "symptoms_en": "Black powdery masses in grains.", "symptoms_hi": "दाने में काला चूर्ण जैसा पदार्थ।", "cause": "Ustilago fungi", "organic_treatment": "Hot water seed treatment.", "chemical_treatment": "Carboxin seed treatment.", "prevention": "Certified treated seeds only.", "severity": "medium"},
    {"name_en": "Sheath Blight", "name_hi": "शीथ ब्लाइट", "crop_affected": "Rice", "symptoms_en": "Elliptical lesions on sheath near waterline.", "symptoms_hi": "तने के आवरण पर अंडाकार धब्बे।", "cause": "Rhizoctonia solani", "organic_treatment": "Trichoderma in soil and reduced humidity.", "chemical_treatment": "Validamycin spray.", "prevention": "Avoid dense planting and excess nitrogen.", "severity": "high"},
    {"name_en": "Leaf Curl Virus in Chilli", "name_hi": "मिर्च पत्ती मुड़न वायरस", "crop_affected": "Chilli", "symptoms_en": "Leaves curl upward and plants become bushy.", "symptoms_hi": "पत्तियां ऊपर मुड़ना और पौधा झाड़ी जैसा।", "cause": "Virus via whitefly", "organic_treatment": "Neem spray and trap crops.", "chemical_treatment": "Acetamiprid for vector control.", "prevention": "Healthy seedlings and weed control.", "severity": "high"},
    {"name_en": "Damping Off", "name_hi": "आधार गलन", "crop_affected": "Nursery seedlings", "symptoms_en": "Seedlings collapse near soil line.", "symptoms_hi": "नर्सरी पौधे जड़ के पास से गिर जाते हैं।", "cause": "Soil borne fungi", "organic_treatment": "Solarized nursery media and Trichoderma.", "chemical_treatment": "Captan seed treatment.", "prevention": "Avoid overwatering and dense sowing.", "severity": "medium"},
]

weather_advice_data = [
    {"condition": "Hot Dry", "temp_min": 40, "temp_max": 55, "rain_probability_min": 0, "advice_en": "Reduce irrigation frequency and apply mulch.", "advice_hi": "सिंचाई अंतराल बढ़ाएं और मल्च लगाएं।", "crop_action": "Protect young plants from heat stress.", "irrigation_advice": "Early morning drip irrigation only."},
    {"condition": "Heavy Rain Alert", "temp_min": 20, "temp_max": 35, "rain_probability_min": 70, "advice_en": "Avoid irrigation and ensure field drainage.", "advice_hi": "सिंचाई रोकें, खेत में जल निकास रखें।", "crop_action": "Stake vegetables and drain standing water.", "irrigation_advice": "No irrigation for 24-48 hours."},
    {"condition": "Frost Alert", "temp_min": -5, "temp_max": 5, "rain_probability_min": 0, "advice_en": "Cover young plants and avoid fresh sowing.", "advice_hi": "नवीन पौधों को ढकें, नई बुवाई टालें।", "crop_action": "Use smoke and light irrigation in evening.", "irrigation_advice": "Light irrigation before dawn."},
    {"condition": "Optimal Growth", "temp_min": 20, "temp_max": 28, "rain_probability_min": 20, "advice_en": "Good weather for sowing and transplanting.", "advice_hi": "बुवाई और रोपाई के लिए अच्छा मौसम।", "crop_action": "Proceed with normal farm operations.", "irrigation_advice": "Maintain regular schedule."},
    {"condition": "Humid Risk", "temp_min": 24, "temp_max": 34, "rain_probability_min": 30, "advice_en": "Watch fungal diseases and spray preventive fungicide.", "advice_hi": "फफूंद रोग पर नजर रखें, रोकथाम स्प्रे करें।", "crop_action": "Improve spacing and air flow.", "irrigation_advice": "Avoid overhead irrigation."},
    {"condition": "Hailstorm Warning", "temp_min": 10, "temp_max": 25, "rain_probability_min": 60, "advice_en": "Protect with net/temporary cover where possible.", "advice_hi": "संभव हो तो जाल या ढकाव से सुरक्षा करें।", "crop_action": "Harvest mature produce early.", "irrigation_advice": "Pause irrigation."},
    {"condition": "High Wind", "temp_min": 18, "temp_max": 34, "rain_probability_min": 15, "advice_en": "Support tall plants and avoid spraying now.", "advice_hi": "ऊंचे पौधों को सहारा दें, स्प्रे टालें।", "crop_action": "Secure polyhouse and trellis.", "irrigation_advice": "Normal irrigation if soil dry."},
    {"condition": "Foggy Morning", "temp_min": 6, "temp_max": 18, "rain_probability_min": 20, "advice_en": "Delay spraying until clear sunlight.", "advice_hi": "धूप निकलने तक स्प्रे रोकें।", "crop_action": "Monitor late blight and mildew.", "irrigation_advice": "Light irrigation only if needed."},
    {"condition": "Moderate Rain", "temp_min": 20, "temp_max": 30, "rain_probability_min": 45, "advice_en": "Reduce irrigation and monitor weeds.", "advice_hi": "सिंचाई कम करें और खरपतवार देखें।", "crop_action": "Top-dress fertilizer after rain stops.", "irrigation_advice": "Skip one cycle."},
    {"condition": "Drought Signal", "temp_min": 30, "temp_max": 45, "rain_probability_min": 5, "advice_en": "Prioritize critical irrigation and moisture conservation.", "advice_hi": "आवश्यक सिंचाई को प्राथमिकता दें, नमी बचाएं।", "crop_action": "Use mulching and anti-transpirants.", "irrigation_advice": "Drip/furrow irrigation at longer intervals."},
    {"condition": "Cold Wave", "temp_min": 2, "temp_max": 12, "rain_probability_min": 10, "advice_en": "Avoid irrigation at night and protect nurseries.", "advice_hi": "रात में सिंचाई न करें, नर्सरी सुरक्षित रखें।", "crop_action": "Use row covers.", "irrigation_advice": "Irrigate during midday only."},
    {"condition": "Warm Cloudy", "temp_min": 25, "temp_max": 33, "rain_probability_min": 35, "advice_en": "Good for vegetative growth but watch insects.", "advice_hi": "पौध बढ़वार अच्छी, पर कीट निगरानी करें।", "crop_action": "Install sticky traps.", "irrigation_advice": "Normal, based on soil moisture."},
    {"condition": "Light Drizzle", "temp_min": 18, "temp_max": 27, "rain_probability_min": 30, "advice_en": "Useful moisture, avoid extra irrigation.", "advice_hi": "अतिरिक्त सिंचाई से बचें, नमी पर्याप्त है।", "crop_action": "Weeding and interculture can continue.", "irrigation_advice": "Postpone irrigation for 1 day."},
    {"condition": "Heat + Humidity", "temp_min": 30, "temp_max": 40, "rain_probability_min": 40, "advice_en": "Risk of pest outbreak, scout fields daily.", "advice_hi": "कीट प्रकोप का खतरा, रोज निरीक्षण करें।", "crop_action": "Use integrated pest management.", "irrigation_advice": "Short and frequent irrigation."},
    {"condition": "Cool Pleasant", "temp_min": 15, "temp_max": 24, "rain_probability_min": 25, "advice_en": "Favorable for most rabi crops.", "advice_hi": "अधिकांश रबी फसलों के लिए अनुकूल।", "crop_action": "Proceed with sowing and fertilizer application.", "irrigation_advice": "Standard schedule."},
]

soil_profiles_data = [
    {"soil_type": "Alluvial", "state": "Punjab, Uttar Pradesh, Bihar", "ph_range": "6.5-8.0", "nutrients": "Potash and lime rich, moderate nitrogen", "suitable_crops": "Wheat, Rice, Sugarcane, Maize", "not_suitable": "Waterlogging sensitive crops without drainage", "improvement_tips_hi": "जैविक खाद बढ़ाएं, सूक्ष्म पोषक तत्व परीक्षण कराएं।"},
    {"soil_type": "Black/Regur", "state": "Maharashtra, Gujarat, MP", "ph_range": "7.2-8.5", "nutrients": "Clay rich, good moisture retention, lime rich", "suitable_crops": "Cotton, Soybean, Sorghum, Turmeric", "not_suitable": "बहुत कम जलनिकास वाली सब्जियां", "improvement_tips_hi": "गहरी जुताई करें और जलनिकास नालियां बनाएं।"},
    {"soil_type": "Red/Laterite", "state": "Tamil Nadu, Karnataka, Odisha", "ph_range": "5.5-7.0", "nutrients": "Low organic matter and nitrogen", "suitable_crops": "Groundnut, Millets, Pulses", "not_suitable": "उच्च पोषण मांगने वाली फसलें बिना सुधार", "improvement_tips_hi": "जैविक खाद, चूना और फॉस्फोरस का उपयोग करें।"},
    {"soil_type": "Sandy/Desert", "state": "Rajasthan, Haryana", "ph_range": "7.0-8.5", "nutrients": "Low water holding and low nutrients", "suitable_crops": "Bajra, Moong, Sesame, Castor", "not_suitable": "अधिक पानी मांगने वाली फसलें", "improvement_tips_hi": "मल्चिंग करें, ड्रिप सिंचाई अपनाएं, गोबर खाद डालें।"},
    {"soil_type": "Loamy", "state": "Many Indian states", "ph_range": "6.0-7.5", "nutrients": "Balanced texture and fertility", "suitable_crops": "Vegetables, Wheat, Mustard, Potato", "not_suitable": "कोई विशेष नहीं, पर जलभराव से बचाएं", "improvement_tips_hi": "फसल चक्र अपनाएं और नियमित मिट्टी जांच करें।"},
    {"soil_type": "Clay/Clayey", "state": "West Bengal, Assam, parts of UP", "ph_range": "6.5-8.0", "nutrients": "High nutrient retention, poor aeration", "suitable_crops": "Rice, Jute, Sugarcane", "not_suitable": "जड़ फसलें जहां जलनिकास खराब हो", "improvement_tips_hi": "बालू और जैविक पदार्थ मिलाएं, जलनिकास बेहतर करें।"},
]


def seed_database():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        db.query(Crop).delete()
        db.query(GovtScheme).delete()
        db.query(Disease).delete()
        db.query(WeatherAdvice).delete()
        db.query(SoilProfile).delete()

        db.bulk_insert_mappings(Crop, crops_data)
        db.bulk_insert_mappings(GovtScheme, schemes_data)
        db.bulk_insert_mappings(Disease, diseases_data)
        db.bulk_insert_mappings(WeatherAdvice, weather_advice_data)
        db.bulk_insert_mappings(SoilProfile, soil_profiles_data)
        db.commit()
        print("Database seeded successfully.")
    except Exception as exc:
        db.rollback()
        print(f"Seeding failed: {exc}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_database()
